version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - WEB_USERNAME=admin
      - WEB_PASSWORD=2301768@SIT.singaporetech.edu.sg
    restart: unless-stopped

  git-server:
    build:
      context: .
      dockerfile: gitserver.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GIT_AUTHOR_NAME=AUSTON IAN NG
      - GIT_AUTHOR_EMAIL=2301768@sit.singaporetech.edu.sg
      - GIT_COMMITTER_NAME=AUSTON IAN NG
      - GIT_COMMITTER_EMAIL=2301768@sit.singaporetech.edu.sg
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
